# Site settings
title: 기괴인간 Yongjun
url: "https://yongjunleeme.github.io"
baseurl: ""
description: >
    기괴인간 블로그

# My information
email: chesidyong@gmail.com
author: 기괴인간 Yongjun
profile: 인생풍요는 배움과 나눔에
twitter_username: 
github_username: yongjunleeme
comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
disqus:
  id: johngrib
  shortname: johngrib
utterances:
  repo: johngrib/johngrib.github.io
  issue-term: pathname
  label: Comment
  branch: master

google_analytics:
  ua: UA-110224147-1

google_adsense:
  client: ca-pub-3675948545737694

blame: "https://github.com/yongjunleeme/yongjunleeme.github.io/blame/master/_wiki"
edit: "https://github.com/yongjunleeme/yongjunleeme.github.io/edit/master/_wiki"
issue: "https://github.com/yongjunleeme/yongjunleeme.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
